services:
  postgres:
    image: postgres:latest
    container_name: storefront_container
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
